/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvaliacaoCapilarCuritibaRouteImport } from './routes/avaliacao-capilar-curitiba'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ProdutosCapilaresRouteImport } from './routes/produtos-capilares'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TratamentoCapilarCuritibaRouteImport } from './routes/tratamento-capilar-curitiba'
import { Route as TratamentoQuedaDeCabeloCuritibaRouteImport } from './routes/tratamento-queda-de-cabelo-curitiba'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPrimeiroAcessoRouteImport } from './routes/admin/primeiro-acesso'
import { Route as ProdutosCapilaresIndexRouteImport } from './routes/produtos-capilares/index'
import { Route as ProdutosCapilaresSlugRouteImport } from './routes/produtos-capilares/$slug'
import { Route as AdminDepartamentosIndexRouteImport } from './routes/admin/departamentos/index'
import { Route as AdminDepartamentosDepartmentIdRouteImport } from './routes/admin/departamentos/$departmentId'
import { Route as AdminDepartamentosNovoRouteImport } from './routes/admin/departamentos/novo'
import { Route as AdminPapeisIndexRouteImport } from './routes/admin/papeis/index'
import { Route as AdminPapeisNovoRouteImport } from './routes/admin/papeis/novo'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin/produtos/index'
import { Route as AdminProdutosSlugRouteImport } from './routes/admin/produtos/$slug'
import { Route as AdminSegurancaSenhaRouteImport } from './routes/admin/seguranca/senha'
import { Route as AdminUsuariosIndexRouteImport } from './routes/admin/usuarios/index'
import { Route as AdminUsuariosUserIdRouteImport } from './routes/admin/usuarios/$userId'
import { Route as AdminUsuariosNovoRouteImport } from './routes/admin/usuarios/novo'
import { Route as AdminPapeisRoleIdIndexRouteImport } from './routes/admin/papeis/$roleId/index'
import { Route as AdminPapeisRoleIdPermissoesRouteImport } from './routes/admin/papeis/$roleId/permissoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoCapilarCuritibaRoute =
  AvaliacaoCapilarCuritibaRouteImport.update({
    id: '/avaliacao-capilar-curitiba',
    path: '/avaliacao-capilar-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosCapilaresRoute = ProdutosCapilaresRouteImport.update({
  id: '/produtos-capilares',
  path: '/produtos-capilares',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentoCapilarCuritibaRoute =
  TratamentoCapilarCuritibaRouteImport.update({
    id: '/tratamento-capilar-curitiba',
    path: '/tratamento-capilar-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const TratamentoQuedaDeCabeloCuritibaRoute =
  TratamentoQuedaDeCabeloCuritibaRouteImport.update({
    id: '/tratamento-queda-de-cabelo-curitiba',
    path: '/tratamento-queda-de-cabelo-curitiba',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrimeiroAcessoRoute = AdminPrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutosCapilaresIndexRoute = ProdutosCapilaresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosCapilaresRoute,
} as any)
const ProdutosCapilaresSlugRoute = ProdutosCapilaresSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosCapilaresRoute,
} as any)
const AdminDepartamentosIndexRoute = AdminDepartamentosIndexRouteImport.update({
  id: '/departamentos/',
  path: '/departamentos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartamentosDepartmentIdRoute =
  AdminDepartamentosDepartmentIdRouteImport.update({
    id: '/departamentos/$departmentId',
    path: '/departamentos/$departmentId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDepartamentosNovoRoute = AdminDepartamentosNovoRouteImport.update({
  id: '/departamentos/novo',
  path: '/departamentos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPapeisIndexRoute = AdminPapeisIndexRouteImport.update({
  id: '/papeis/',
  path: '/papeis/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPapeisNovoRoute = AdminPapeisNovoRouteImport.update({
  id: '/papeis/novo',
  path: '/papeis/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosSlugRoute = AdminProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegurancaSenhaRoute = AdminSegurancaSenhaRouteImport.update({
  id: '/seguranca/senha',
  path: '/seguranca/senha',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosIndexRoute = AdminUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosUserIdRoute = AdminUsuariosUserIdRouteImport.update({
  id: '/usuarios/$userId',
  path: '/usuarios/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosNovoRoute = AdminUsuariosNovoRouteImport.update({
  id: '/usuarios/novo',
  path: '/usuarios/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPapeisRoleIdIndexRoute = AdminPapeisRoleIdIndexRouteImport.update({
  id: '/papeis/$roleId/',
  path: '/papeis/$roleId/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPapeisRoleIdPermissoesRoute =
  AdminPapeisRoleIdPermissoesRouteImport.update({
    id: '/papeis/$roleId/permissoes',
    path: '/papeis/$roleId/permissoes',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avaliacao-capilar-curitiba': typeof AvaliacaoCapilarCuritibaRoute
  '/carrinho': typeof CarrinhoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/produtos-capilares': typeof ProdutosCapilaresRouteWithChildren
  '/termos': typeof TermosRoute
  '/tratamento-capilar-curitiba': typeof TratamentoCapilarCuritibaRoute
  '/tratamento-queda-de-cabelo-curitiba': typeof TratamentoQuedaDeCabeloCuritibaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/primeiro-acesso': typeof AdminPrimeiroAcessoRoute
  '/produtos-capilares/$slug': typeof ProdutosCapilaresSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/produtos-capilares/': typeof ProdutosCapilaresIndexRoute
  '/admin/departamentos/$departmentId': typeof AdminDepartamentosDepartmentIdRoute
  '/admin/departamentos/novo': typeof AdminDepartamentosNovoRoute
  '/admin/papeis/novo': typeof AdminPapeisNovoRoute
  '/admin/produtos/$slug': typeof AdminProdutosSlugRoute
  '/admin/seguranca/senha': typeof AdminSegurancaSenhaRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/admin/departamentos/': typeof AdminDepartamentosIndexRoute
  '/admin/papeis/': typeof AdminPapeisIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/admin/papeis/$roleId/permissoes': typeof AdminPapeisRoleIdPermissoesRoute
  '/admin/papeis/$roleId/': typeof AdminPapeisRoleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacao-capilar-curitiba': typeof AvaliacaoCapilarCuritibaRoute
  '/carrinho': typeof CarrinhoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos': typeof TermosRoute
  '/tratamento-capilar-curitiba': typeof TratamentoCapilarCuritibaRoute
  '/tratamento-queda-de-cabelo-curitiba': typeof TratamentoQuedaDeCabeloCuritibaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/primeiro-acesso': typeof AdminPrimeiroAcessoRoute
  '/produtos-capilares/$slug': typeof ProdutosCapilaresSlugRoute
  '/admin': typeof AdminIndexRoute
  '/produtos-capilares': typeof ProdutosCapilaresIndexRoute
  '/admin/departamentos/$departmentId': typeof AdminDepartamentosDepartmentIdRoute
  '/admin/departamentos/novo': typeof AdminDepartamentosNovoRoute
  '/admin/papeis/novo': typeof AdminPapeisNovoRoute
  '/admin/produtos/$slug': typeof AdminProdutosSlugRoute
  '/admin/seguranca/senha': typeof AdminSegurancaSenhaRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/admin/departamentos': typeof AdminDepartamentosIndexRoute
  '/admin/papeis': typeof AdminPapeisIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/admin/usuarios': typeof AdminUsuariosIndexRoute
  '/admin/papeis/$roleId/permissoes': typeof AdminPapeisRoleIdPermissoesRoute
  '/admin/papeis/$roleId': typeof AdminPapeisRoleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avaliacao-capilar-curitiba': typeof AvaliacaoCapilarCuritibaRoute
  '/carrinho': typeof CarrinhoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/produtos-capilares': typeof ProdutosCapilaresRouteWithChildren
  '/termos': typeof TermosRoute
  '/tratamento-capilar-curitiba': typeof TratamentoCapilarCuritibaRoute
  '/tratamento-queda-de-cabelo-curitiba': typeof TratamentoQuedaDeCabeloCuritibaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/primeiro-acesso': typeof AdminPrimeiroAcessoRoute
  '/produtos-capilares/$slug': typeof ProdutosCapilaresSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/produtos-capilares/': typeof ProdutosCapilaresIndexRoute
  '/admin/departamentos/$departmentId': typeof AdminDepartamentosDepartmentIdRoute
  '/admin/departamentos/novo': typeof AdminDepartamentosNovoRoute
  '/admin/papeis/novo': typeof AdminPapeisNovoRoute
  '/admin/produtos/$slug': typeof AdminProdutosSlugRoute
  '/admin/seguranca/senha': typeof AdminSegurancaSenhaRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  '/admin/usuarios/novo': typeof AdminUsuariosNovoRoute
  '/admin/departamentos/': typeof AdminDepartamentosIndexRoute
  '/admin/papeis/': typeof AdminPapeisIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/admin/papeis/$roleId/permissoes': typeof AdminPapeisRoleIdPermissoesRoute
  '/admin/papeis/$roleId/': typeof AdminPapeisRoleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avaliacao-capilar-curitiba'
    | '/carrinho'
    | '/politica-de-privacidade'
    | '/produtos-capilares'
    | '/termos'
    | '/tratamento-capilar-curitiba'
    | '/tratamento-queda-de-cabelo-curitiba'
    | '/admin/login'
    | '/admin/primeiro-acesso'
    | '/produtos-capilares/$slug'
    | '/admin/'
    | '/produtos-capilares/'
    | '/admin/departamentos/$departmentId'
    | '/admin/departamentos/novo'
    | '/admin/papeis/novo'
    | '/admin/produtos/$slug'
    | '/admin/seguranca/senha'
    | '/admin/usuarios/$userId'
    | '/admin/usuarios/novo'
    | '/admin/departamentos/'
    | '/admin/papeis/'
    | '/admin/produtos/'
    | '/admin/usuarios/'
    | '/admin/papeis/$roleId/permissoes'
    | '/admin/papeis/$roleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avaliacao-capilar-curitiba'
    | '/carrinho'
    | '/politica-de-privacidade'
    | '/termos'
    | '/tratamento-capilar-curitiba'
    | '/tratamento-queda-de-cabelo-curitiba'
    | '/admin/login'
    | '/admin/primeiro-acesso'
    | '/produtos-capilares/$slug'
    | '/admin'
    | '/produtos-capilares'
    | '/admin/departamentos/$departmentId'
    | '/admin/departamentos/novo'
    | '/admin/papeis/novo'
    | '/admin/produtos/$slug'
    | '/admin/seguranca/senha'
    | '/admin/usuarios/$userId'
    | '/admin/usuarios/novo'
    | '/admin/departamentos'
    | '/admin/papeis'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/admin/papeis/$roleId/permissoes'
    | '/admin/papeis/$roleId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avaliacao-capilar-curitiba'
    | '/carrinho'
    | '/politica-de-privacidade'
    | '/produtos-capilares'
    | '/termos'
    | '/tratamento-capilar-curitiba'
    | '/tratamento-queda-de-cabelo-curitiba'
    | '/admin/login'
    | '/admin/primeiro-acesso'
    | '/produtos-capilares/$slug'
    | '/admin/'
    | '/produtos-capilares/'
    | '/admin/departamentos/$departmentId'
    | '/admin/departamentos/novo'
    | '/admin/papeis/novo'
    | '/admin/produtos/$slug'
    | '/admin/seguranca/senha'
    | '/admin/usuarios/$userId'
    | '/admin/usuarios/novo'
    | '/admin/departamentos/'
    | '/admin/papeis/'
    | '/admin/produtos/'
    | '/admin/usuarios/'
    | '/admin/papeis/$roleId/permissoes'
    | '/admin/papeis/$roleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvaliacaoCapilarCuritibaRoute: typeof AvaliacaoCapilarCuritibaRoute
  CarrinhoRoute: typeof CarrinhoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ProdutosCapilaresRoute: typeof ProdutosCapilaresRouteWithChildren
  TermosRoute: typeof TermosRoute
  TratamentoCapilarCuritibaRoute: typeof TratamentoCapilarCuritibaRoute
  TratamentoQuedaDeCabeloCuritibaRoute: typeof TratamentoQuedaDeCabeloCuritibaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao-capilar-curitiba': {
      id: '/avaliacao-capilar-curitiba'
      path: '/avaliacao-capilar-curitiba'
      fullPath: '/avaliacao-capilar-curitiba'
      preLoaderRoute: typeof AvaliacaoCapilarCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos-capilares': {
      id: '/produtos-capilares'
      path: '/produtos-capilares'
      fullPath: '/produtos-capilares'
      preLoaderRoute: typeof ProdutosCapilaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamento-capilar-curitiba': {
      id: '/tratamento-capilar-curitiba'
      path: '/tratamento-capilar-curitiba'
      fullPath: '/tratamento-capilar-curitiba'
      preLoaderRoute: typeof TratamentoCapilarCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamento-queda-de-cabelo-curitiba': {
      id: '/tratamento-queda-de-cabelo-curitiba'
      path: '/tratamento-queda-de-cabelo-curitiba'
      fullPath: '/tratamento-queda-de-cabelo-curitiba'
      preLoaderRoute: typeof TratamentoQuedaDeCabeloCuritibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/primeiro-acesso': {
      id: '/admin/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/admin/primeiro-acesso'
      preLoaderRoute: typeof AdminPrimeiroAcessoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produtos-capilares/': {
      id: '/produtos-capilares/'
      path: '/'
      fullPath: '/produtos-capilares/'
      preLoaderRoute: typeof ProdutosCapilaresIndexRouteImport
      parentRoute: typeof ProdutosCapilaresRoute
    }
    '/produtos-capilares/$slug': {
      id: '/produtos-capilares/$slug'
      path: '/$slug'
      fullPath: '/produtos-capilares/$slug'
      preLoaderRoute: typeof ProdutosCapilaresSlugRouteImport
      parentRoute: typeof ProdutosCapilaresRoute
    }
    '/admin/departamentos/': {
      id: '/admin/departamentos/'
      path: '/departamentos'
      fullPath: '/admin/departamentos/'
      preLoaderRoute: typeof AdminDepartamentosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departamentos/$departmentId': {
      id: '/admin/departamentos/$departmentId'
      path: '/departamentos/$departmentId'
      fullPath: '/admin/departamentos/$departmentId'
      preLoaderRoute: typeof AdminDepartamentosDepartmentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departamentos/novo': {
      id: '/admin/departamentos/novo'
      path: '/departamentos/novo'
      fullPath: '/admin/departamentos/novo'
      preLoaderRoute: typeof AdminDepartamentosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/papeis/': {
      id: '/admin/papeis/'
      path: '/papeis'
      fullPath: '/admin/papeis/'
      preLoaderRoute: typeof AdminPapeisIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/papeis/novo': {
      id: '/admin/papeis/novo'
      path: '/papeis/novo'
      fullPath: '/admin/papeis/novo'
      preLoaderRoute: typeof AdminPapeisNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/$slug': {
      id: '/admin/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/admin/produtos/$slug'
      preLoaderRoute: typeof AdminProdutosSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seguranca/senha': {
      id: '/admin/seguranca/senha'
      path: '/seguranca/senha'
      fullPath: '/admin/seguranca/senha'
      preLoaderRoute: typeof AdminSegurancaSenhaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios/': {
      id: '/admin/usuarios/'
      path: '/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AdminUsuariosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios/$userId': {
      id: '/admin/usuarios/$userId'
      path: '/usuarios/$userId'
      fullPath: '/admin/usuarios/$userId'
      preLoaderRoute: typeof AdminUsuariosUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios/novo': {
      id: '/admin/usuarios/novo'
      path: '/usuarios/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AdminUsuariosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/papeis/$roleId/': {
      id: '/admin/papeis/$roleId/'
      path: '/papeis/$roleId'
      fullPath: '/admin/papeis/$roleId/'
      preLoaderRoute: typeof AdminPapeisRoleIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/papeis/$roleId/permissoes': {
      id: '/admin/papeis/$roleId/permissoes'
      path: '/papeis/$roleId/permissoes'
      fullPath: '/admin/papeis/$roleId/permissoes'
      preLoaderRoute: typeof AdminPapeisRoleIdPermissoesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPrimeiroAcessoRoute: typeof AdminPrimeiroAcessoRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDepartamentosDepartmentIdRoute: typeof AdminDepartamentosDepartmentIdRoute
  AdminDepartamentosNovoRoute: typeof AdminDepartamentosNovoRoute
  AdminPapeisNovoRoute: typeof AdminPapeisNovoRoute
  AdminProdutosSlugRoute: typeof AdminProdutosSlugRoute
  AdminSegurancaSenhaRoute: typeof AdminSegurancaSenhaRoute
  AdminUsuariosUserIdRoute: typeof AdminUsuariosUserIdRoute
  AdminUsuariosNovoRoute: typeof AdminUsuariosNovoRoute
  AdminDepartamentosIndexRoute: typeof AdminDepartamentosIndexRoute
  AdminPapeisIndexRoute: typeof AdminPapeisIndexRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
  AdminUsuariosIndexRoute: typeof AdminUsuariosIndexRoute
  AdminPapeisRoleIdPermissoesRoute: typeof AdminPapeisRoleIdPermissoesRoute
  AdminPapeisRoleIdIndexRoute: typeof AdminPapeisRoleIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminPrimeiroAcessoRoute: AdminPrimeiroAcessoRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDepartamentosDepartmentIdRoute: AdminDepartamentosDepartmentIdRoute,
  AdminDepartamentosNovoRoute: AdminDepartamentosNovoRoute,
  AdminPapeisNovoRoute: AdminPapeisNovoRoute,
  AdminProdutosSlugRoute: AdminProdutosSlugRoute,
  AdminSegurancaSenhaRoute: AdminSegurancaSenhaRoute,
  AdminUsuariosUserIdRoute: AdminUsuariosUserIdRoute,
  AdminUsuariosNovoRoute: AdminUsuariosNovoRoute,
  AdminDepartamentosIndexRoute: AdminDepartamentosIndexRoute,
  AdminPapeisIndexRoute: AdminPapeisIndexRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
  AdminUsuariosIndexRoute: AdminUsuariosIndexRoute,
  AdminPapeisRoleIdPermissoesRoute: AdminPapeisRoleIdPermissoesRoute,
  AdminPapeisRoleIdIndexRoute: AdminPapeisRoleIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProdutosCapilaresRouteChildren {
  ProdutosCapilaresSlugRoute: typeof ProdutosCapilaresSlugRoute
  ProdutosCapilaresIndexRoute: typeof ProdutosCapilaresIndexRoute
}

const ProdutosCapilaresRouteChildren: ProdutosCapilaresRouteChildren = {
  ProdutosCapilaresSlugRoute: ProdutosCapilaresSlugRoute,
  ProdutosCapilaresIndexRoute: ProdutosCapilaresIndexRoute,
}

const ProdutosCapilaresRouteWithChildren =
  ProdutosCapilaresRoute._addFileChildren(ProdutosCapilaresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvaliacaoCapilarCuritibaRoute: AvaliacaoCapilarCuritibaRoute,
  CarrinhoRoute: CarrinhoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ProdutosCapilaresRoute: ProdutosCapilaresRouteWithChildren,
  TermosRoute: TermosRoute,
  TratamentoCapilarCuritibaRoute: TratamentoCapilarCuritibaRoute,
  TratamentoQuedaDeCabeloCuritibaRoute: TratamentoQuedaDeCabeloCuritibaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
